### PR TITLE
Use Java8 Time&Date API by D8 Library Desugar

### PR DESCRIPTION
**Pull request by koji-1009**
At AndroidStudio 4.0, we will be able to use *D8 Library Desugar*.

- <https://developer.android.com/studio/preview/features#j8-desugar>
- <https://jakewharton.com/d8-library-desugaring/#backporting-types>

According to the article, we can use `java.time` package instead of `org.threeten.bp` package.
So, I created this a PR.

---

There are two points to request a review.

1. Could you accept changes to D8?
1. Is the code quality okay?

Thanks great library!

### CODE REVIEW

**Comment by koji-1009** [comment]
If you test, check this.
<https://github.com/koji-1009/material-calendarview/tree/patch>

**Comment by fabiankr** [comment]
+1 for this, but maybe increase the library version as this is a breaking change. Desugaring is the way to go and threetenabp is already deprecated.

**Comment by koji-1009** [comment]
It appears that the development of the library has stopped, so I am closing the PR.
Thank you very much.

**Comment by goemic** [comment]
If anyone is still looking for this, I created a fork with with desugaring enabled AND androidx migration. In the fork's readme I updated everything for easy setup and direct jitpack deployment for a v3.0.0 release.

https://github.com/goemic/material-calendarview/blob/master/README.md

**Pull request closed without merging**
