### PR TITLE
Expand Calendar View

### PR DESCRIPTION
**Pull request by Laces**
- Add option to enable/disable dynamic calendar height. By enabling
this, the calendar view will automatically change its height based on
the actual month week number.
- Add option for multiple day selection by long pressing and dragging
- Add option to set a custom day view from the main project to the
library, if the default one is not customizable enough.

### CODE REVIEW

**Comment by Laces** [comment]
```javascript
mCalendarView = (MaterialCalendarView) findViewById(R.id.mycalendarview);
mCalendarView.setEnableDynamicHeight(true);
mCalendarView.setIsMultipleSelection(true);
mCalendarView.setDayViewProvider(new DayViewProvider() {
            @Override
            public View getDayView() {
                return new MyCustomDayView(MainActivity.this);
            }
        });

public class MyCustomDayView extends LinearLayout implements CheckableCalendarDayView {
   ...
}
```

**Comment by dandc87** [comment]
Hey @Laces, thanks for wanting to contribute! Right now, a large change set is coming (#131), which include things like multiple date selection. That's going to cause some merge conflicts here, so I'm going to wait for that before reviewing this.

**Comment by InfinityApps** [comment]
@dandc87 Would it be possible to introduce the dynamic height feature to the library first?

**Comment by dandc87** [comment]
Hey @Laces, could you split this into multiple pull requests, one per feature, and direct the PRs to `future-1.x` branch? It would be great if you could start with dynamic calendar height; it's a popular feature request

**Comment by Laces** [comment]
Hey,
Yes, I`ll do it next monday.
Regards
Laci

**Pull request closed without merging**
