### PR TITLE
add title click listener event.

### PR DESCRIPTION
**Pull request by sasowang**
Good library! add title click event. (it will check minDate maxDate also.)

### CODE REVIEW

**Comment by magneticflux-** [comment]
@sasowang From looking at the code, I understand that this adds adds a dialog when title (between the month arrows) is clicked, that allows the user to select a date to scroll to. Is this correct?

**Comment by sasowang** [comment]
yes, but not a date. user can select and change to the specific month.

**Comment by magneticflux-** [comment]
@sasowang I see, this seems like a good addition if it works on all supported Android versions.

**Comment by sasowang** [comment]
yes. it can support api level 11 above. You can see I add a logic in the function for hide day spinner.

**Comment by quentin41500** [comment]
I do see the benefits to have a listener on the title. However, I do not want to force the user to have the onClickListener showing a dialog. Instead, we should provide a listener for the user to implement his own behavior. Will reject this for now. Sorry for the inconvenience.

**Pull request closed without merging**
