### PR TITLE
Add attributes to change pages by clicking on dates from other months.

### PR DESCRIPTION
**Pull request by Charrondev**
I've added the ability to switch months as per issue #116.

### CODE REVIEW

**Comment by dandc87** [comment]
Thanks for the PR @Charrondev! I have two major issues right now:

1. Your code looks like it should work, but when I pull it down and run the feature doesn't seem to work, at least in the Dynamic Setters Test
2. I'm not sure this needs to be a flag. I don't see the use case of `OUT_OF_RANGE_SELECTABLE` and `OTHER_MONTHS_SELECTABLE` (you should make your range larger if you want to select them), and if you remove them this could just be a boolean attribute. Or even better, it could be another flag on `showOtherDates`, since you probably only want it when other months are shown anyways.

**Comment by Charrondev** [comment]
Thanks for the input. I'll be going through it soon and working on the suggested changes.

**Comment by ekchang** [comment]
Are you still working on this? You've deleted your fork and have reverted most of your changes. Closing for now.

If you do plan to continue working on this feature, please direct your PR toward branch `future/1.x` instead of master.

**Comment by caltseng** [comment]
:( I was looking forward to this.

**Pull request closed without merging**
