### PR TITLE
horizontal tile spacing

### LINKED ISSUE #132: Horizontal tile spacing
Hi @dandc87, I just started experimenting with the library (versions 0.8.1 and 1.0.0-beta1) and I think it's awesome! I'm wondering if it's possible to set the tile size and still make the view fill all of the horizontal space. Currently, if I set the tile size to something smaller than the default 44dp, the tiles group together in the center, leaving padding on the left and right sides of the calendar. Basically, I'm trying to reduce the overall height of the calendar view, while still making it fill the horizontal space of the screen.

This is what I'm doing in XML:

    <com.prolificinteractive.materialcalendarview.MaterialCalendarView
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

And then in Java:

    calendarView.setTileSizeDp(38);

Here's a screenshot of what the calendar looks like:

screenshot_2015-09-20-17-54-19

And here's a screenshot of roughly what I'm going for:

screenshot_2015-09-20-18-00-00

Thanks in advance!
-Dan

### PR DESCRIPTION
**Pull request by chrissd23**
Hi, 

This commit should fix #132

### CODE REVIEW

**Comment by chrissd23** [comment]
Sorry for my commit i try to squash , but i did some mistakes

**Comment by leigo** [comment]
The dayViewDecorator is squashed.How to fix it?

**Comment by AntaresR** [comment]
Hi how is the update doing?

**Comment by leigo** [comment]
See [https://github.com/leigo/material-calendarview](https://github.com/leigo/material-calendarview)

**Comment by AntaresR** [comment]
Ty pal, you people are live savers.

@leigo

**Comment by ekchang** [comment]
Can you modify the PR to point to `future-1.x` instead of master?

**Comment by quentin41500** [comment]
It seems that your PR breaks the ripple effect on 5.1.1. A better approach would be to allow the user to set tileWidth and tileHeight independently.

screenshot_2016-05-04-12-02-53

**Comment by quentin41500** [comment]
@ekchang I suppose we can close this PR now. You can use attributes: `mcv_tileWidth` and `mcv_tileHeight` or the java methods.

**Comment by ekchang** [comment]
This feature has been added as part of 1.3

**Comment by smithshelke** [comment]
the selection drawable is stretched horizontally when tileWidth and tileHeight are set to match_parent

**Pull request closed without merging**
