### PR TITLE
Support match_parent as a valid tile dimension

### PR DESCRIPTION
**Pull request by Maragues**
You can now pass match_parent to tileSize, tileWidth and tileHeight

Closes https://github.com/prolificinteractive/material-calendarview/issues/349

### CODE REVIEW

**Comment by Maragues** [comment]
I also had to upgrade the gradle plugin, let me know if that's a problem and I will revert that.

**Comment by quentin41500** [comment]
@Maragues Could you please target your PR to the future-1.x branch ?

**Comment by quentin41500** [comment]
You might have to delete this PR and create a new one.

**Comment by quentin41500** [comment]
Im not sure this is completely needed after all, we might not need to have a `match_parent` for the tile size. We just need the user to be able to reset the sizes after setting is to something.

**Comment by Maragues** [comment]
@quentin41500 If you read the description of issue https://github.com/prolificinteractive/material-calendarview/issues/349 you'll see that right now setting a value for either height or width sets the other dimension to the default value unless you specify the size, that's why this PR is needed (or at least its goal).

I'll do as you ask tomorrow.

**Pull request closed without merging**
