### PR TITLE
Fix issue where month representations weren't being generated correctly

### PR DESCRIPTION
**Pull request by dandc87**
This should fix issue #74. @sersast @gusdn9 @jlindenbaum can any of you try out the a snapshot build `'com.prolificinteractive:material-calendarview:0.7.0-SNAPSHOT'` to verify this fixes the issue?

Reviewers: @ireneduke @chahinem

### CODE REVIEW

**Comment by sersast** [comment]
I get the following error while building:
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.prolificinteractive:material-calendarview:0.7.0-SNAPSHOT.
     Searched in the following locations:
         https://jcenter.bintray.com/com/prolificinteractive/material-calendarview/0.7.0-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/com/prolificinteractive/material-calendarview/0.7.0-SNAPSHOT/material-calendarview-0.7.0-SNAPSHOT.pom
         https://jcenter.bintray.com/com/prolificinteractive/material-calendarview/0.7.0-SNAPSHOT/material-calendarview-0.7.0-SNAPSHOT.jar
         file:/devapps/Android/sdk/extras/android/m2repository/com/prolificinteractive/material-calendarview/0.7.0-SNAPSHOT/maven-metadata.xml
         file:/devapps/Android/sdk/extras/android/m2repository/com/prolificinteractive/material-calendarview/0.7.0-SNAPSHOT/material-calendarview-0.7.0-SNAPSHOT.pom
         file:/devapps/Android/sdk/extras/android/m2repository/com/prolificinteractive/material-calendarview/0.7.0-SNAPSHOT/material-calendarview-0.7.0-SNAPSHOT.jar
         file:/devapps/Android/sdk/extras/google/m2repository/com/prolificinteractive/material-calendarview/0.7.0-SNAPSHOT/maven-metadata.xml
         file:/devapps/Android/sdk/extras/google/m2repository/com/prolificinteractive/material-calendarview/0.7.0-SNAPSHOT/material-calendarview-0.7.0-SNAPSHOT.pom
         file:/devapps/Android/sdk/extras/google/m2repository/com/prolificinteractive/material-calendarview/0.7.0-SNAPSHOT/material-calendarview-0.7.0-SNAPSHOT.jar
     Required by:
         ULF:app:unspecified

**Comment by jlindenbaum** [comment]
Same for me.

**Comment by dandc87** [comment]
@sersast @jlindenbaum @gusdn9 You also need to add maven's staging repository. It should look something like this (likely under `allprojects` in your top level `build.gradle`):
```groovy
repositories {
    jcenter()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

**Comment by sersast** [comment]
It doesn't work either. The following error pops up (among other non-resolved dependencies):
   > Could not find com.android.support:support-v4:22.2.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
         https://jcenter.bintray.com/com/android/support/support-v4/22.2.0/support-v4-22.2.0.jar
         https://oss.sonatype.org/content/repositories/snapshots/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
         https://oss.sonatype.org/content/repositories/snapshots/com/android/support/support-v4/22.2.0/support-v4-22.2.0.jar
         file:/devapps/Android/sdk/extras/android/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
         file:/devapps/Android/sdk/extras/android/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.jar
         file:/devapps/Android/sdk/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
         file:/devapps/Android/sdk/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.jar
     Required by:
         ULF:app:unspecified > com.prolificinteractive:material-calendarview:0.7.0-SNAPSHOT

**Comment by dandc87** [comment]
@sersast thats weird, I'm not sure what could have been messed up. We just need `maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }` added after any `jcenter()` or `mavenCentral()` in your build.gradle files. That shouldn't break anything.

**Comment by jlindenbaum** [comment]
@sersast I have two places for `repositories`. Throw it into both, and it worked for me.

Just testing now, will report back in a few.

**Comment by jlindenbaum** [comment]
This snapshot version works for me! Thanks so much.

**Comment by sersast** [comment]
Yes it works :)
I just had to update "Google repositories" in the SDK manager.
@dandc87 Thanks for this awesome library and the time you invest in it.

**Pull request merged**
