### PR TITLE
Support custom fonts

### PR DESCRIPTION
**Pull request by anasanasanas**
Support custom fonts for all calendar text.

### CODE REVIEW

**Comment by Niroj08** [comment]
There are four issues for custom font support. Why this PR is still not merged? I too want this fix ASAP.

**Comment by Niroj08** [comment]
What I did was cloned this project and then merged the PR of @anasanasanas into local repo , and used it as the module in my android project.
Thank you @anasanasanas  for the fix. Hope someone to merge the PR.
My bad, I could not get future updates :) hope everything I need is available

**Comment by anasanasanas** [comment]
@Niroj08 you can use my fork I usually merge their updates to my fork.
    compile 'com.github.anasanasanas:material-calendarview:1.4.4'

**Comment by Niroj08** [comment]
@anasanasanas great ..
Also I am addressing one issue. 
While the date range is selected, the fonts are changed to default. 
and again if the range is dis-selected the font are restored back.

**Comment by anasanasanas** [comment]
thanks @Niroj08 for pointing this out,  I will open issue in my fork and will solve it ASAP
https://github.com/anasanasanas/material-calendarview

**Comment by rajscet** [comment]
check my answer here. you can easily set up custom font: Rajesh Nasit

https://stackoverflow.com/questions/33923803/how-to-set-custom-font-for-a-whole-application-in-android/42218846#42218846

**Comment by Niroj08** [comment]
@rajscet thank you for the help. but that was not what I wanted. I could have a better solution than that :)
@anasanasanas  I hope compile 'com.github.anasanasanas:material-calendarview:1.4.4' is not working. 
Failed to resolve ... during gradle build..

**Comment by rajscet** [comment]
Niroj08 can you tell me that solution?

**Comment by anasanasanas** [comment]
@Niroj08 
in the main gradle file add this:

allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}

**Comment by iad24** [comment]
Can help put here example on how to change the font? I cant find it in the examples. thanks

**Comment by Niroj08** [comment]
https://github.com/prolificinteractive/material-calendarview/issues/611

**Comment by tevjef** [comment]
Closing in favor on #782

**Pull request closed without merging**
