### PR TITLE
Fix Decorator Selection Drawable

### LINKED ISSUE #72: setSelectionDrawable(Drawable drawable) not working for me
Hi,
What I want is to mark selected date with drawable from resources (PNG file). I took BasicActivity from sample application and added this code:

        DayViewDecorator decorator = new DayViewDecorator() {
            @Override
            public boolean shouldDecorate(CalendarDay day) {
                return true;
            }

            @Override
            public void decorate(DayViewFacade view) {
                if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                    view.setSelectionDrawable(getDrawable(R.drawable.select_date));
                } else {
                    view.setSelectionDrawable(ContextCompat.getDrawable(BasicActivity.this, R.drawable.select_date));
                }
            }
        };
        widget.addDecorator(decorator);

Unfortunately when I select a date only default, blue, circle background is displayed. Am I missing something?

### PR DESCRIPTION
**Pull request by dandc87**
This fixes #72 by 'cloning' the custom drawable set via decorators. It also adds an example in the sample app for custom selectors.

### CODE REVIEW

**Comment by ireneduke** [comment]
Why did you put the drawables in mipmap folders? I thought those were mostly for launcher icons.

**Comment by ireneduke** [comment]
Also, why aren't you using the prolific code style for this project?

**Comment by dandc87** [comment]
There wasn't really a reason for using mipmap, so I changed it. 

For code styling, the best reason I have is because I want to make it easier for people to contribute, since Android Studio uses 4 spaces by default. But I also started the project on my home machine, which doesn't have the Prolific style setup.

**Comment by dandc87** [comment]
@ireneduke is this good to merge?

**Comment by ireneduke** [comment]
:+1:

**Pull request merged**
