### PR TITLE
Added method setTopbarVisibility(boolean) which allows the user to se…

### LINKED ISSUE #63: flag to hide a month header
Thank you for awesome calendarview first!

Is there any optional flag to hide a month header?
I want to hide it as I'm trying to display current month text in actionbar title like google calendar

### PR DESCRIPTION
**Pull request by bigbhowell**
…t the visibility of the calendar topbar. Added private LinearLayout field topbar to accomplish. Fixes #63

### CODE REVIEW

**Comment by dandc87** [comment]
Hey @bigbhowell, could you rename it to `setTopbarVisible()`? After that, I'm good to merge it.

**Comment by chahinem** [comment]
Maybe its better to pass the visibility itself as a parameter 
`public void setTopbarVisibility(int visibility)`

**Comment by dandc87** [comment]
@chahinem what would be the use case of setting the top bar to INVISIBLE?

**Comment by chahinem** [comment]
@dandc87 ooh, I haven't thought about this case. Then i'm ok

**Comment by bigbhowell** [comment]
@dandc87 not a problem at all.

**Pull request merged**
